# Generated by Django 5.1.7 on 2025-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=199.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('science', 'Science'), ('fantasy', 'Fantasy')], default='fiction', max_length=50),
        ),
    ]
